# CSwL's Makefile — builds the book in its four variants.
#
# Each variant produces `_out/<variant>/{html,lean}`:
#
#   student    full prose, answer keys elided (become `sorry`)
#              -> the cut that becomes the GitHub Classroom assignment and
#                 the published HTML book
#   solutions  full prose, answer keys shown
#              -> answer key, published after each submission
#   terse      lecture prose, answer keys elided and `workinclass!` proofs
#              stubbed -> opened in VS Code during class
#   grading    full prose, answer keys shown plus `import AutograderLib`
#              and the `[autogradedProof …]` attributes -> never leaves the
#              private repository; it's what
#                 lake exe autograder --local <submission> <file>
#              runs against
#
# `_out/<variant>/lean/` is a standalone Lake project (with its own
# `lakefile.toml` and `lean-toolchain`), generated by
# `CSwLMeta/Save/Project.lean`. `lean4-autograder-main` is a dependency only
# of the `grading` variant's generated project -- never of CSwL's own
# `lakefile.toml`, where it would collide with the Mathlib that `cslib`
# brings.
#
# The `Literate`/`build-web.sh` pipeline was retired on 08/16: all four
# chapters are already in the `Manual` genre, and the book is only built
# from here.

.PHONY: all student solutions terse grading build serve clean publish-book

default: all

all: student solutions terse grading

# Builds the executable before running any variant. On subsequent calls
# Lake notices nothing changed and exits immediately.
build:
	lake build cswl-book

student: build
	lake exe cswl-book student

solutions: build
	lake exe cswl-book solutions

terse: build
	lake exe cswl-book terse

grading: build
	lake exe cswl-book grading

# Serves all four variants at http://127.0.0.1:8000/ (each under
# `<variant>/html/`), with Verso's own server -- configured in
# `verso-serve.toml`. Replaces the old `python3 -m http.server -d _out/`.
serve: all
	lake build verso-serve
	lake exe verso-serve

clean:
	rm -rf _out/

# Publica o _out/student/ já construído no repositório `book` (sibling
# checkout, `../book` por padrão): lean/ vai para o branch main, html/ vai
# para o branch gh-pages. Não depende de `student` — rode `make student`
# antes; publish-book só sincroniza e dá push no que já foi buildado.
publish-book:
	scripts/publish-book.sh
